### ISSUE TITLE
Code worked once, now core dumped

### ISSUE THREAD

**Issue by zabop** [dfm/python-nufft#10]
I had a code which worked, now it does not, and I think it has to do something with the fortran part of the package. It is described here:
https://stackoverflow.com/questions/52392709/code-worked-once-now-core-dumped-from-nufft-algorithm-what-went-wrong
Is this only me, or is it a general issue?
Cheers:)

**Comment by szabozoltan69** [comment]
I also received this error with the above ^ [script.py](https://pastebin.com/T7GfbkMq):
python3 script.py
```*** Error in `python3': double free or corruption (out): 0x00000000030ce6e0 ***```
Details:
https://pastebin.com/E6qZLF9y

**Comment by szabozoltan69** [comment]
I found some information about this bug here: https://github.com/tensorflow/tensorflow/issues/6968
And if I use this workaround ( https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-273959067 ), apt install libtcmalloc-minimal4, export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4", then (running the script) I receive a more verbose explanation: ```Traceback (most recent call last):
  File "script.py", line 14, in <module>
    max_index = np.abs(ft[1:]).tolist().index(max_value)
ValueError: nan is not in list```

**Comment by zabop** [comment]
Change the line specifying f to` f=np.linspace(0.95,1.05,10000)`, and it'll work
